### PR TITLE
Initial stab at making an article about meanders top-level macros

### PR DESCRIPTION
**Pull request by jimmyhmiller**
Happy for any change to be made/suggested by anyone.

### CODE REVIEW

**Comment by noprompt** [comment]
This is fantastic! We can merge this whenever you'd like. If you'd like to see if anyone is interested in offering some feedback, that'd be fine too.

**Review by dgr — COMMENTED** [review]
Overall looks good. Found a typo in the second sentence, however: "At first glance it might not be obvious **with** function you should use..."

**with** -> **which**

**Comment by jimmyhmiller** [comment]
@dgr thanks!

**Comment by dgr** [comment]
@jimmyhmiller my pleasure!

**Review by noprompt — APPROVED** [review]

**Pull request merged**
